### ISSUE TITLE
直接上传就可以用吗，还是像上一个版本那样

### ISSUE THREAD

**Issue by 2131411** [ikxin/kms-tools#10]
直接上传就可以用吗，还是像上一个版本那样需要修改kms服务器为自己的才可以用
还有跟第一个版本通用吗？更新直接覆盖可以吗？更新后以前kms激活的是否可以继续使用

**Comment by ikxin** [comment]
直接上传就可以，kms服务器可以自行输入

**Comment by ikxin** [comment]
专门为你出了一期视频
https://www.bilibili.com/video/BV1SF411K7bq

**Comment by 2131411** [comment]
> 是你本期视频 https://www.bilibili.com/video/BV1SF411K7bq

非常感谢非常感谢
