### ISSUE TITLE
Unable to switch language

### ISSUE THREAD

**Issue by whalelinguni** [ikxin/kms-tools#26]
Sorry, this is not really an 'issue' I see there are language settings. I do not see any documentation on changing to English, but I can see lang info in vue devtools, but I am unsure how/where to change it. I tried translating to search easier. 

I cannot seem to find this. Can you provide information on how to change?

**Comment by ikxin** [comment]
It is a bug and has been fixed. You can try https://kms.ikxin.com

![QQ_1724205294471](https://github.com/user-attachments/assets/72096658-6913-4968-8709-24ef11c123db)

**Comment by ikxin** [comment]
Closed. Please feel free to reopen if needed.
