### ISSUE TITLE
请求加入 windows server 2025 等 最新版

### ISSUE THREAD

**Issue by LeticiaAnna** [ikxin/kms-tools#28]
一直在用贵站的工具，目前已经推出 Windows server 2025 win 11 LTS 等，工具似乎还未引入，故申请

**Comment by ikxin** [comment]
感谢认可，我关注到 https://learn.microsoft.com/en-us/windows-server/get-started/kms-client-activation-keys 确实更新了许多新版本的 License Keys，将它更新到现在的版本也许很快，但我最近计划使用 nuxt 重构该项目，以抛弃 bun 和 elysia 这些比较大的包袱，所以更新会稍微延后一些。

**Comment by LeticiaAnna** [comment]
感谢作者！

**Comment by ikxin** [comment]
@LeticiaAnna 已更新 Windows Server 2025、Windows 11 LTSC 2024、Office 2024 LTSC 等最新密钥
